#!/bin/sh
#	Created by Volarics Istvan by Voli

#:::::: Fix beallitasok :::::::
#:::::: Beallitasok :::::::::::
#:::::: Fuggvenyek ::::::::::::
#:::::::: Start :::::::::::::::

fail2ban-client status|grep -e "- Jail list:" |sed 's/.*Jail list://g; s/,//g; s/ \+/\n/g;' |while read a; do

    echo ""
    fail2ban-client status $a |grep -v "Banned IP list:" |grep -e "Status for the jail:" -e "Currently banned:" -e "Total banned:"
done
