#!/bin/bash
#	Created by Volarics Istvan by Voli

#:::::: Fix beallitasok :::::::
DIR=/usr/src/linux

MAKE_PARAM=" -j 4 "		#Több szálu forditas

CONF_SOR=CONFIG_LOCALVERSION=
#:::::: Beallitasok :::::::::::
#:::::: Fuggvenyek ::::::::::::
InitRD(){
	Version=`readlink ${DIR}|sed 's/^.*-//g;'`\
`cat ${DIR}/.config|grep "${CONF_SOR}"|sed "s/$CONF_SOR//g; s/\"//g; "`

	echo "Aktuális verziószám: ${Version}"
	/usr/sbin/update-initramfs -c -k "${Version}"

	if [ ".$?" != ".0" ]; then
		/usr/sbin/update-initramfs -u -k "${Version}"
	fi
}

#:::::::: Start :::::::::::::::
	cd "${DIR}"
	[ $? -ne 0 ] && exit 1

	if [ -z "$1" ]; then 
		echo "Usage: $0 {Menu|Torles|Kernel|kernel Install|MODul|Modul Install|INITramfs|Full deb}";
		exit 2
	fi

case "$1" in
      m)	echo "Menu config...";
	    make menuconfig;
	    ;;

      t)	echo "Torles...  "; 
	    make dep; 				[ $? -ne 0 ] && exit 1
	    make clean; 			[ $? -ne 0 ] && exit 1
	    make mrproper; 			[ $? -ne 0 ] && exit 1
	    ;;

      k)	echo "Kernel forditas..."
	    make ${MAKE_PARAM} bzImage; 	[ $? -ne 0 ] && exit 1
	    ;;

      i)	echo "Csak kernel install..."
	    make install; 			[ $? -ne 0 ] && exit 1
	    ;;

      init)
	    InitRD
	    ;;

      mod)	echo "Modul forditas..."
	    make ${MAKE_PARAM} modules; 	[ $? -ne 0 ] && exit 1
	    ;;

      mi)	echo "Modules Install..."
	    make modules_install; 		[ $? -ne 0 ] && exit 1
	    ;;

      deb)	echo "Debian csomag készitése..."
	    make ${MAKE_PARAM} KDEB_PKGVERSION=1 deb-pkg; 	[ $? -ne 0 ] && exit 1
	    ;;

      f)	echo "Minden..."
	    $0 k; 				[ $? -ne 0 ] && exit 1
	    $0 mod; 				[ $? -ne 0 ] && exit 1
	    $0 mi; 				[ $? -ne 0 ] && exit 1
	    $0 init; 				[ $? -ne 0 ] && exit 1
	    $0 i; 				[ $? -ne 0 ] && exit 1
	    ;;

      *)
	    echo "Hibás paraméter: /$1-"; 	exit 1;
esac
    echo "Sikeres..."

    shift;
    if [ -n ".$*" ]; then
	$0 $*
    fi
