#!/bin/bash
#	Created by Volarics Istvan by Voli

## Az okosságom forrása: https://www.tbsiptv.com/index.php?route=product/download/drivers&path=download/tbs6590/tbs6590_multi_standard_dual_tuner_dual_ci_pcie_card_data_sheet.pdf&id=39

#:::::: Fix beallitasok :::::::
MAKE_PARAM=" -j 4 "		#Több szálu forditas

#:::::: Beallitasok :::::::::::
DIR=/usr/src/tbsdriver
FILE_FIND=FindFile.lst
FILE_CSERE=Csere.lst

FW_URL="http://www.tbsdtv.com/download/document/linux/"
FW_FILE="tbs-tuner-firmwares_v1.0.tar.bz2"

#:::::: Fuggvenyek ::::::::::::
Dir_save(){
	SavePath=$( pwd )
	[ ! -e $DIR ] && mkdir -p $DIR ; 	[ $? -ne 0 ] && exit 1
	cd $DIR ; 				[ $? -ne 0 ] && exit 2
}
Dir_restore(){
	cd $SavePath
}

Letoltes(){
    echo "Mindent törlök, majd letöltöm a forrásokat..."
    cd $DIR ; 										[ $? -ne 0 ] && exit 1
    rm -rf ./media ./media_build ${FILE_FIND} ${FILE_CSERE} 	2>&1 1>/dev/null
    git clone https://github.com/tbsdtv/media_build.git ; 				[ $? -ne 0 ] && exit 2
    git clone --depth=1 https://github.com/tbsdtv/linux_media.git -b latest ./media ; 	[ $? -ne 0 ] && exit 3
    rm -rf ./media/.git ./media_build/.git
}
Forditas(){
    echo "És akkor a fordítás..."
    cd $DIR/media_build ; 	[ $? -ne 0 ] && exit 1
    make dir DIR=../media ; 	[ $? -ne 0 ] && exit 2
    make distclean ; 		[ $? -ne 0 ] && exit 3
    make $MAKE_PARAM ; 		[ $? -ne 0 ] && exit 4
}
Install(){
    echo "Install..."
    cd $DIR/media_build ; 	[ $? -ne 0 ] && exit 1
    sudo make install ; 	[ $? -ne 0 ] && exit 11
}

VerzioCsere(){			## $1: A verzió, pl.: '5.4.0-38-generic'
    cd $DIR ; 	[ $? -ne 0 ] && exit 1
    find . |grep -v "/Documentation/" |sort |while read fn; do
	[ -d $fn ] && continue

	grep  -c "uname -r" $fn >/dev/null ; Ret=$?
	[ ${Ret} -ne 0 ] && continue

	echo ">>>>>>>>>>>>>>>>>>>$fn<<<<<<<<"
	echo "$fn" 	>>${FILE_FIND}
	grep -e "uname -r"  $fn
	echo "------------------------------"

	sed -i "s/\$(shell uname -r |/\$(shell echo $1 |/g" 	$fn
	sed -i "s/\$(shell uname -r)/$1/g" 				$fn
	sed -i "s/\$(shell,uname -r)/$1/g" 				$fn

	sed -i "s/\$(uname -r |/\$(echo $1 |/g" 	$fn
	sed -i "s/\$(uname -r)/$1/g" 			$fn

	sed -i "s/@uname -r|/@echo $1|/" 		$fn
	sed -i "s/\`uname -r\`/$1/g" 			$fn
	sed -i "s/'uname -r'/$1/g" 			$fn

	grep -e "$1" -e "uname -r" $fn 		## Mi lett a csere után
    done |tee -a ${FILE_CSERE}
}
Verzio(){
    if [ -z $1 ]; then echo "Nincs megadva a verzió amire fordítsak"; 			exit 1; fi
    if [ ! -e /lib/modules/$1 ]; then 	echo "Nincs ilyen ($1) kernel verzió..."; 	exit 2; fi

    DIR=$DIR/$1
    [ ! -e ${DIR} ] && mkdir ${DIR}

    Letoltes
    VerzioCsere $1
    Forditas
    Install
    Dir_restore
}

do_teszt(){
	dmesg |grep -e si2183 -e si2157 -e frontend
	dmesg |grep TBS |sed 's/.*\]//'|sort -u
}
do_Delete(){
    ls  $DIR|while read fn; do
	echo "$fn";
	echo rm -rf $DIR/$fn
    done
}
do_Firmware(){
    Dir_save
    [ -e $FW_FILE ] && rm $FW_FILE
    wget "${FW_URL}${FW_FILE}" ; 		[ $? -ne 0 ] && exit 1
    tar jxvf "${FW_FILE}" -C /lib/firmware/ ; 	[ $? -ne 0 ] && exit 2
    Dir_restore
}
do_Full(){
    Dir_save
    Letoltes
    Forditas
    Install
    Dir_restore
}
do_Verzio(){
    if [ -z "$1" ]; then
	echo "A második paraméterben meg kell adni a verziót..."
	echo "úgy ahogy azt az 'uname -r' írja ki. pl: '5.4.0-38-generic'."
	echo ""
	echo " A lehetséges verziók listája:"
	ls  /boot|grep vmlinuz |sed 's/^vmlinuz-/\t/'
	exit 1
    fi
    Verzio $1
}

#:::::::: Start :::::::::::::::
case "$1" in
	t|T)
	    do_teszt
	;;
	d|d)
	    do_Delete
	;;
	w|W)
	    do_Firmware
	;;
	f|F)
	    do_Full
	;;
	v|V)
	    do_Verzio $2
	;;
      *)
	    echo "Usage: $0 t|w|f|v|d [a konkrét verzió]"
	    echo "	(T)eszt: 	Kernel logot iratki a TBS-ről."
	    echo "	(D)elete: 	Letörli a rorrásokat és fordításokat."
	    echo "	(F)ull: 	Az aktuális kernelhez, letölti a netről, fordítja, és telepíti."
	    echo "	firm(W)are: 	A firmware-t telepíti."
	    echo "	(V)erzio a_verzio_amire_forditani_akasz. A megadott vrzióra fordit."
	exit 1;
esac
