#!/bin/sh
#
#	Create by Voli

#:::::: Fix beallitasok :::::::
#:::::: Beallitasok :::::::::::
#:::::: Ellenorzesek ::::::::::
#:::::: functions :::::::::::::
Hash_torol(){
ls  Screenshot_*.jpg	2>/dev/null |sort	|while read a; do
				#Screenshot_2022-02-11-12-48-30-42.jpg
	b=$( echo "$a" |sed 's|_[0-9a-f]*\.jpg|.jpg|g; ' )
	if [ "$a" = "$b" ]; 	then continue; fi
	c=$( echo "$b" |sed 's|\(Screenshot_[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\)-\([0-9]\{2\}-[0-9]\{2\}\)-\([0-9]\{2\}\)-|\1_\2-\3|' )
	if [ "$a" = "$c" ]; 	then continue; fi
	if [ -e "$c" ]; 	then continue; fi
	echo "$a ===> $c"
	mv "$a" "$c"
done
}

IMG(){
ls  IMG*.jpg IMG*.png	2>/dev/null |sort	|while read a; do
				#IMG_20210202_115744.jpg
	b=$( echo "$a" |sed 's|IMG_*\([0-9]\{4\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)|IMG_\1-\2-\3|; ' )
#echo --------------------$a///////////////$b-----------
	if [ "$a" = "$b" ]; 	then continue; fi
	if [ -e "$b" ]; 	then continue; fi
	echo "$a ===> $b"
	mv "$a" "$b"
done
}

#:::::: Start :::::::::::::::::

#Screenshot_2022-02-11-12-48-30-42_bd54b661362b80c5a7eecc75e487a121.jpg
	Hash_torol
	IMG
