#!/bin/sh
#	Created by Volarics Istvan by Voli

#:::::: Fix beallitasok :::::::
MINTA_FILE_ELOTAG=Voli_
DIR_MUNKA=/tmp/lc

LIB_DIR=/var/lib/logcheck
LOGFILE_LISTA=/etc/logcheck/logcheck.logfiles
KIVETELEK_DIR=/etc/logcheck/ignore.d.server

#:::::: Beallitasok :::::::::::
DIR_KIVETELEK=${DIR_MUNKA}/Regi
DIR_KIVETELEK_UJ=${DIR_MUNKA}/Uj

KIVETELEK_GYARI_FILE=${DIR_MUNKA}/Kivetelek_gyari
KIVETELEK_SAJAT_FILE=${DIR_MUNKA}/Kivetelek_sajat
LOG_MIND=${DIR_MUNKA}/Minden.log
LOG_NO_GYARI=${DIR_MUNKA}/MindenNoGyari.log
LOG_NO_SAJAT=${DIR_MUNKA}/MindenNoGyariNoSajat.log
LOG_BOOT_KERNEL=${DIR_MUNKA}/boot-tol_kernel.log
TmpFile=${DIR_MUNKA}/kivetel.tmp

#:::::: Fuggvenyek :::::::::::: BELSŐ
Logok_egybe(){
    echo "A logok összegyüjtése..."
    [ ! -e $DIR_MUNKA/tmp ] && mkdir -p $DIR_MUNKA/tmp
    rm $DIR_MUNKA/tmp/* >/dev/null 2>&1
    mkdir -p $DIR_MUNKA/tmp
    cat $LOGFILE_LISTA|grep -v "^#"|while read a; do
	cp $a* $DIR_MUNKA/tmp/
    done
    gzip -d 	$DIR_MUNKA/tmp/*.gz
    cat 	$DIR_MUNKA/tmp/* |sort -u >$LOG_MIND
}
Kivetelek_sajat_egy_helyre(){
    [ ! -e $DIR_KIVETELEK    ] && mkdir $DIR_KIVETELEK
    [ ! -e $DIR_KIVETELEK_UJ ] && mkdir $DIR_KIVETELEK_UJ
    echo "Regi minták összegyüjtése..."
    find /etc/logcheck |grep -e "$MINTA_FILE_ELOTAG" |while read a; do
	cp "$a" "$DIR_KIVETELEK/"
    done
}
Kivetelek_sajat_egybe(){
    echo "Sajat kivételek egy file-ba..."
    [ ! -e $DIR_MUNKA ] && mkdir -p $DIR_MUNKA
    find ${KIVETELEK_DIR} |grep "$MINTA_FILE_ELOTAG" |sort |while read f ; do
	[ -d "$f" ] && continue
	cat "$f"
    done |grep -v -e "^#" -e "^$" |sort -u >${KIVETELEK_SAJAT_FILE}
}
Kivetelek_gyari_egybe(){
    echo "Gyári kivételek egy file-ba..."
    find ${KIVETELEK_DIR} |grep -v "$MINTA_FILE_ELOTAG" |sort |while read f ; do
	[ -d "$f" ] && continue
	cat "$f"
    done |grep -v -e "^#" -e "^$" |sort -u >${KIVETELEK_GYARI_FILE}
}




#:::::: Fuggvenyek ::::::::::::
do_mail(){
    echo "Levél küldése..."; 
    sudo -u logcheck logcheck
}
do_mail_uj(){
    echo "A teljes log-ra levél küldés..."
    rm $LIB_DIR/*
    sudo -u logcheck logcheck
}
do_aktiv(){
    echo "A saját (${MINTA_FILE_ELOTAG}) előtaguakból, csak az marad meg amelyik érvényes sort tartalmaz..."
    echo "Itt fogod megtalálni az új mintákat tartalmazó file-okat: >>${DIR_KIVETELEK_UJ}<<"
    Logok_egybe
    Kivetelek_sajat_egy_helyre
    echo "Az eggyes file-ok feldolgozása..."
    ls $DIR_KIVETELEK/ |while read fname; do
	echo "===>> $fname"
	[ -e "${DIR_KIVETELEK_UJ}/${fname}" ] && rm  "${DIR_KIVETELEK_UJ}/${fname}"
	cat "${DIR_KIVETELEK}/${fname}" |sed 's|\\|\\\\|g' |while read sor; do
	    [ -z "$sor" ] && echo "" >>"${DIR_KIVETELEK_UJ}/${fname}"
	    [ -z "$sor" ] && continue
	    echo  "$sor"  >${TmpFile}
	    grep -c -E -f ${TmpFile} $LOG_MIND >/dev/null
	    [ $? -ne 0 ] && continue
	    echo  "$sor" >>"${DIR_KIVETELEK_UJ}/${fname}"
	done
	[ ! -e "${DIR_KIVETELEK_UJ}/${fname}" ] && continue 		## Csak üres sorokat tartalmazókat töröljük
	grep -c -v -e "^$" "${DIR_KIVETELEK_UJ}/${fname}" 	>/dev/null
	[ $? -eq 1 ] && rm "${DIR_KIVETELEK_UJ}/${fname}"
    done
    chown root:logcheck ${DIR_KIVETELEK_UJ}/*
    [ -e ${TmpFile} ] && rm ${TmpFile}
}
do_nem_szurt(){
    echo "Azokat a sorokat írja ki a log-okból melyeket nem szürtünk ki..."
    Logok_egybe
    Kivetelek_gyari_egybe
    Kivetelek_sajat_egybe
    echo "A logok-ból kiszedem a gyári mintákat..."
    grep -v -E -f ${KIVETELEK_GYARI_FILE} ${LOG_MIND} >${LOG_NO_GYARI}
    echo "A logok-ból kiszedett gyári minták után a sajátokat is kitakarítom..."
    grep -v -E -f ${KIVETELEK_SAJAT_FILE} ${LOG_NO_GYARI} >${LOG_NO_SAJAT}
    echo "Az időbélyeget lecserélve, az azonosakat kiszürve..."
    sed 's|^.\{15\}|Abc 00 00:00:00|; s|\[[0-9]\+\]|\[0230\]| ' ${LOG_NO_SAJAT} |sort -u >${LOG_NO_SAJAT}_
}

#:::::::: Start :::::::::::::::

do_kernel_boot(){
    echo "A boot-tól eltelt kernel üzenetek szürve a saját kivételekkel ==> kivétel készítése, hogy mind benne legyen"
    Kivetelek_sajat_egybe
    journalctl -b |grep -e '^\w\{3\} [ :0-9]\{11\} [._[:alnum:]-]\+ kernel:' 	>$LOG_BOOT_KERNEL
echo 11111
    grep -v -E -f ${KIVETELEK_SAJAT_FILE} $LOG_BOOT_KERNEL 		>${LOG_BOOT_KERNEL}.1
echo 22222
    sed 's|^.\{16\}||' ${LOG_BOOT_KERNEL}.1 >${LOG_BOOT_KERNEL}.2
echo 33333
    sort -u ${LOG_BOOT_KERNEL}.2 >${LOG_BOOT_KERNEL}.3

}


#do_kernel_boot
#echo ............; read a; exit 0

case "$1" in
	mail)
	    do_mail
	;;
	mail-uj)
	    do_mail_uj
	;;
	aktiv)
	    do_aktiv
	;;

	szuretlen)
	    do_nem_szurt
	;;
      *)
	echo "$0 [check|mail|mail-uj|sajat-uj]"
	echo ""
	echo "mail: 	lefuttatja a logcheck-et."
	echo "mail-uj: 	Letörli a jelölést, hogy meddig volt az ellenenőrzés, és le futtatja a logcheck-et."
	echo "aktiv: 	A \"${DIR_KIVETELEK_UJ}\" könyvtárba a régi kivételekből azokat teszi amelyek MOST adnak találatot."
	echo "szuretlen: Azok a sorok maradnak amelyekre ninvs szűrés,"
	echo ""
esac
