#!/bin/sh
#	Created by Volarics Istvan by Voli

#:::::: Fix beallitasok :::::::
#:::::: Beallitasok :::::::::::
#:::::: Fuggvenyek ::::::::::::
#:::::::: Start :::::::::::::::
cp /usr/lib/chromium-browser/libffmpeg.so /usr/lib/x86_64-linux-gnu/opera
