#!/bin/bash
#
#	Create by Voli

#:::::: Fix beallitasok :::::::
DIR="/sys/devices/system/cpu/cpufreq/policy[0-9]*"

#:::::: Beallitasok :::::::::::
CPU_FREQ_min=$[$( cat ${DIR}/cpuinfo_min_freq|sort -u )/1000]
CPU_FREQ_max=$[$( cat ${DIR}/cpuinfo_max_freq|sort -u )/1000]


#:::::: Ellenorzesek ::::::::::
#:::::: functions :::::::::::::
#:::::: Start :::::::::::::::::
    echo "usage: "$(basename $0)" [management]"
    if [ -n "$1" ]; then
	echo Meg probalom beaalitani az uj managementet ($1)....
	for x in $( ls ${DIR}/scaling_governor ); do
		echo -n "$1" 	>>$x
	done
    fi

    echo "CPU frekvencia, min: ${CPU_FREQ_min} Mhz; max: ${CPU_FREQ_max} MHz."
    echo -n "Lehetseges CPU frekvencia management(ek): "; cat ${DIR}/scaling_available_governors |sort -u
    echo -n "Aktualis   CPU frekvencia management(ek): "; cat ${DIR}/scaling_governor 		 |sort -u

    cnt=0
    while true; do
	echo -ne "\r\n${cnt}: "
	for x in ${DIR}/scaling_cur_freq ; do
	    s=$[$( cat $x )/1000]
	    if [ $s -le ${CPU_FREQ_min} ]; then
		echo -ne "\t....."
	    elif [ $s -lt 1000 ]; then
		echo -ne "\t  $s"
	    else
		echo -ne "\t$s"|sed 's/\(^\t.\)/\1\./g'
	    fi
	done
	cnt=$[${cnt}+1]; sleep 1
    done
