#!/bin/bash
#
#	Create by Voli

#:::::: Fix beallitasok :::::::
DIR=/sys/devices/system/cpu/cpufreq/policy*

#:::::: Beallitasok :::::::::::
Freq_Min=$( cat ${DIR}/cpuinfo_min_freq |sort    |grep -m 1 "." |sed 's/000$//' )
Freq_Max=$( cat ${DIR}/cpuinfo_max_freq |sort -r |grep -m 1 "." |sed 's/000$//' )

 cat ${DIR}/cpuinfo_min_freq |sort    |grep -m 1 "." |sed 's/000$//'

#:::::: Ellenorzesek ::::::::::
#:::::: functions :::::::::::::
#:::::: Start :::::::::::::::::
    echo "usage: "$(basename $0)" [management]"
    if [ -n "$1" ]; then
	echo "Meg probalom beaalitani az uj managementet ($1)...."
	for x in $( ls ${DIR}/scaling_governor ); do
		echo -n "$1" 	>>$x
	done
    fi

    CPU_Type=$(  cat /proc/cpuinfo |grep -c "vendor_id" )		## Ha nem nulla akkor intel

    Tomb=$( ls $DIR/affected_cpus |grep -c "." )
    if [ $CPU_Type != 0 ] ; then
	Core=$( cat /proc/cpuinfo |grep "^cpu cores" |sort -u|sed 's/.*://g; ' )
	Szal=$( cat /proc/cpuinfo |grep "^siblings"  |sort -u|sed 's/.*://g; ' )
	echo "CPU magok: $Core, szálak: $Szal , tömb(ök): $Tomb."
    else
	Core=$(  cat /proc/cpuinfo |grep -c -e "processor" )
	Tipus=$( cat /proc/cpuinfo |sort -u |grep -c -e "CPU variant" )
	echo "CPU magok: $Core, tipussal: $Tipus , tömb(ök): $Tomb."
    fi

    echo "/////////${Freq_Max}///////////"

    echo "CPU frekvencia, min: $Freq_Min Mhz max: $Freq_Max  MHz."
    echo -n "Lehetseges CPU frekvencia management(ek): "; cat ${DIR}/scaling_available_governors |sort -u 	#Így mindegyiket csak 1-szer írja ki
    echo -n "Aktualis   CPU frekvencia management(ek): "; cat ${DIR}/scaling_governor 		 |sort -u

    cnt=0
    while true; do
	echo -ne "\r\n${cnt}: "
	for x in ${DIR}/scaling_cur_freq ; do
	    s=$[$( cat $x )/1000]
	    if [ $s -le ${Freq_Min} ]; then
		echo -ne "\t....."
	    elif [ $s -lt 1000 ]; then
		echo -ne "\t  $s"
	    else
		echo -ne "\t$s"|sed 's/\(^\t.\)/\1\./g'
	    fi
	done
	cnt=$[${cnt}+1]; sleep 1
    done
