#!/bin/bash
#	Created by Voli & Emre volaricsi@gmail.com
#	Rendszermasolo

SYS_SOURCE=sda2
SYS_IDE=sdb2
SOURCE="/mnt/$SYS_SOURCE"
HOVA="/mnt/$SYS_IDE"

#A file-ban ($1) átír mindent $SYS_SOURCE --> $SYS_IDE
Atiras()
{	mv ${HOVA}$1 ${HOVA}$1.${SYS_SOURCE}			1>&2	2>/dev/null
	cat ${HOVA}$1.${SYS_SOURCE}|sed "s/$SYS_SOURCE/$SYS_IDE/g"	>${HOVA}$1
}

#Csak a könyvtárat hozzuk létre
MkDir()
{   if [ ! -e "$HOVA/$a" ]; then 
	mkdir "$HOVA/$a"
	chmod 755 "$HOVA/$a"
    fi
}

#Csatolási pont létrehozása
if [ ! -r "$HOVA" ];	then	mkdir "$HOVA";		fi
if [ ! -r "$SOURCE" ];	then	mkdir "$SOURCE";	fi

#felcsatolások, a forrás elég ha csak olvasható
mount 	/dev/$SYS_IDE $HOVA		#	1>&2	2>/dev/null
mount 	/dev/$SYS_SOURCE $SOURCE	#	1>&2	2>/dev/null

#a root file system másolása
for a in `ls $SOURCE/|sort`; do
    echo `date`: ${a}

    case ".${a}" in

    #A kihagyott könytárak
	    .lost+found)
		MkDir "$a"
	    ;;
    #Maga a könyvtár másolása
	    *)
		echo `date`: cp -apdR "$SOURCE/$a"	"$HOVA/$a" >>$HOVA/syscp$$
		cp -apdR "$SOURCE/$a" "$HOVA/$a" >>$HOVA/syscp$$ 2>&1
	    ;;
    esac

done

#File-ban atirasok, hogy jó legyen....
umount $SOURCE
umount $HOVA
echo Vege. press key....
echo `date`: Vege. press key.... >>$HOVA/syscp$$
read
