#!/bin/sh
#	Created by Volarics Istvan by Voli

	uname -a
	lsb_release -a 	2>/dev/null
    if [ -e /etc/debian_version ]; then
	    echo -n "Debian version: "
	    cat /etc/debian_version
    fi
    if [ -e /etc/hostname ]; then
	    echo -n "Hostname: "
	    cat /etc/hostname
    fi
    echo Host nevek:
	hostname --alias
	hostname --all-fqdns
	hostname --fqdn

